# config
logo: /images/StormCloudsGathering.png
keywords: "Logic, Science, History, Geopolitics, Psychology, Design Philosophy, Permaculture, Group Psychology, Primal Psychology, Economic Psychology"
pubkey:

# Content
excerpt_link: Read more

# Miscellaneous
rss: /rss.xml
google_analytics:

# Sidebar
links_title: Sources