# config
logo: /images/branding/StormCloudsGathering.png
keywords: "Logic, Science, History, Geopolitics, Psychology, Design Philosophy, Permaculture, Group Psychology, Primal Psychology, Economic Psychology"
pubkey:

# Content
excerpt_link: Read more

# Miscellaneous
rss: /rss.xml
twitter: '@SCGupdates'
google_plus: https://plus.google.com/+StormCloudsGathering
fb_admins: 511446393
fb_app_id: 514568561907093