# config
logo: /images/svdb.png
keywords: "Logic, Psychology, Economics, Geopolitics"
pubkey:
menu:
  Home: /
  Articles: /articles
  About: /about

# Content
excerpt_link: Read more

# Miscellaneous
rss: /rss.xml
google_analytics:
