# config
logo: /images/StormCloudsGathering.png
keywords: "Geopolitics, Logic, Science, Design Philosophy, Permaculture, Psychology, Group Psychology, Primal Psychology, Economic Psychology"
pubkey:
menu:
  Home: /
  Articles: /articles
  About: /about

# Content
excerpt_link: Read more

# Miscellaneous
rss: /rss.xml
google_analytics:

# Sidebar
widgets:
- links
- tag